[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[env]
GOPRIVATE = "github.com/takai/*"
GONOSUMDB = "github.com/takai/*"
GONOPROXY = "github.com/takai/*"
GOPROXY = "direct"

[tools]
ruby = "4.0"
go = "1.25"
usage = "latest"
ghq = "latest"
fzf = "latest"

"github:takai/git-ai-commit" = "latest"

"go:github.com/takai/yt-transcript/cmd/yt-transcript" = "latest"
"go:github.com/takai/naduke/cmd/naduke" = "latest"
